### SELECT 문법
- LIMIT : 가져올 수 있는 데이터 중 일부만 가져오고 싶을 때
- COUNT (* 집계함수) : 데이터의 총 개수를 확인하고 싶을 때
- DISTINCT : 특정 값을 가져올 때, 중복된 값을 출력하지 않고 싶을 때 -> 범주형 데이터
- SUM : 해당 컬럼값의 합계 -> 수치형 데이터
- AVG : 해당 컬럼값의 합계 -> 수치형 데이터
- MAX : 해당 컬럼값의 최대값 -> 수치형 데이터
- MIN : 해당 컬럼값의 최소값 -> 수치형 데이터
- GROUP BY : 특정 컬럼값을 기반으로 그룹핑하기
  - SELECT rating FROM film GROUP BY rating -> film이라는 테이블에서 rating값을 찾아오는데 해당 rating의 값을 그룹화해서 찾아와라!
  - SELECT COUNT(*) FROM film GROUP BY rating -> 각 rating 값의 종류별로 몇개의 데이터가 있는지 확인
  - SELECT COUNT(*) FROM film WHERE 조건문 GROUP BY rating -> 특정 조건에 맞는 데이터 중 rating값의 종류별로 몇 개의 데이터가 있는지 확인
- ORDER BY : 특정 컬럼값을 기준으로 데이터를 정렬 (* 오름차순 = ASC, 내림차순 = DESC)
  - 만약 DESC, ASC 중 그 어떤 값을 입력하지 않는다면, 기본 값은 ASC 정렬로 실행

...
SELECT 컬럼명
FROM 테이블명
WHERE 조건절
GROUP BY 컬럼
ORDER BY 컬럼
LIMIT 출력갯수

## DATA 대분류 리스트
1) 수치형 데이터 : (1,2,1.1 등)
2) 범주형 데이터 : (남/여, 미성년/성인 등) -> 중복값 제거해야하는 경우가 많음

### SQL 중급 단계
1) FOREIGN KEY (외래 키) <-> PRIMARY KEY (고유 키)
2) HAVING
    - HAVING절을 활용해서 조건 비교
    - WHERE절을 활용해서도 조건 비교가 가능한데 왜 굳이 HAVING절이 필요할까?
    - 특정 테이블 내 데이터를 그룹핑하는 GROUP BY절을 적용한 상태에서 집계함수가 표현된 조건식을 사용하려고 할 때 반드시 HAVING절을 사용해야함
3) JOIN (*실제 실무에서도 굉장히 많이 사용되는 기능)
   - 1개의 테이블에 너무 많은 방대한 데이터를 몰아넣는 경우는 없음
   - 복수의 테이블을 관리하는 경우가 빈번 -> 각각의 테이블간 연결고리를 FOREIGN KEY를 만들어 놓고, 해당 테이블간 연결하는 경우가 숙명적으로 많을 수 밖에 없음 -> 그래서 JOIN 문법을 많이 사용함
   - 서로 다른 테이블을 하나의 연결된 테이블로 활용하고자 할 때 사용
   - INNER JOIN : 서로 다른 테이블간 매칭되는 데이터에 한해서 해당 데이터를 기준으로 연결 (*JOIN이라는 문법을 사용하면 default가 INNER JOIN이기 때문에 실무에서는 INNER수식어 생략 가능)
   - 서로 다른 테이블을 하나로 연결하기 위해서는 어떤 테이블을 기준으로 연결할 것인가? -> ON 전치사  
   - OUTER JOIN : 서로 매칭되지 않는 데이터도 모두 찾아옴 (*T상대적으로 많이 사용하지 않음)
       - LEFH OUTER JOIN : 먼저 언급된 (*LEFT DATA = 부모 데이터) 를 기준으로 다른 테이블을 연결, 자식데이터에 부모데이터와 매칭되지 않은 데이터가 존재하더라도 해당 데이터를 누락시키지 않고 찾아옴
       - RIGHT OUTER JOIN : 자식데이터를 기준으로 다른 테이블을 연결, 마찬가지로 매칭되지 않은 데이터들을 누락시키지 않고 모두 찾아옴
4) SubQuery
    - SQL문 안에 포함되어있는 SQL문 -> 중첩 SQL문
5) INDEX
    - 파이썬 > 리스트 > 리스트 자료구조 내부에 있는 아이켐들에게 각각 인덱스 값 부여
    - SQL 구문을 활용해서 컬럼 안에 입력되어있는 데이터들에게 개별적인 인덱스 값을 부여 -> 값을 서칭해서 찾아오는 빈도 잦음 -> 너무 많은 시간, 과정 (효율성 높음)
    - 인덱스 종류
      - 클러스터형 인덱스 : 영어 사전과 같은 형태로 데이터를 정렬한다고 생각 ex. PRIMARY KEY // FOREIGN KEY // UNOQUE
      - 보조 인덱스 : 데이터는 그대로 둔 상태에서 마치 책으로 비유하면 책 끝 부분에 있는 찾아보기 인덱스(색인) 정도로 생각
        - SHOW INDEX FROM customers;   # 특정 테이블 내 인덱스 값 조회
        - ALTER TABLE userTbl ADD CONSTRAINT TESTdate UNIQUE (mDate); # 보조 인덱스 생성 방법
        - CREATE INDEX idx_birth ON userTbl(birthYear); # 보조 인덱스 생성 방법
        - ALTER TABLE userTbl ADD INDEX idx_addr(addr);  # 보조 인덱스 생성 방법
        - ALTER TABLE userTbl DROP INDEX idx_addr;  # 보조 인덱스 삭제 방법

#### 무신사 브랜드 사용할 것 같은 느낌으로 TABLE 생성 -> 마케터의 관점에서 어떻게 사용해보면 좋을까
- 고객 테이블 (*고객 정보 가지고 있는 데이터 -> 나이, 성별, 주소, 이메일, 전화번호등)
- 상품 테이블 (*상품 정보 가지고 있는 데이터 -> 재고, 메인카테고리, 서브카테고리, 상품가격, 할인가격, 할인률 등)
- 주문 테이블 (*주문 정보 가지고 있는 데이터 -> 주문수량, 주문한 날짜, 외래 키 -> 고객 & 상품)
  리뷰 테이블 (*리뷰 정보 가지고 있는 데이터 -> 평점, 리뷰내용, 리뷰작성 날짜, 외래키 -> 고객 & 상품)

## 데이터 분석 마케터
- 자사 매출 증대를 목표 -> 마케팅
- 회원들의 등급을 파악하고 해당 등급에 따른 차별화된 CRM 마케팅을 해야겠다는 생각
- 회원등급별 인원수 -> 가장 많은 등급에 속해있는 사용자들을 분석해서 페르소나화 해야겠다
- 결론 : 회원등급별 인원수 출력

...
- 자사몰에서 상품을 판매중 -> 꾸준하게 잘 판매되고 있는 상품과 그렇지 않은 상품을 구분
- 잘 판매되고 있는 상품은 지속적으로 신규고객 및 충성고객 확보를 목표
- 판매실적이 좋지 않은 상품은 단종 || 리뉴얼 재고 관리
- 결론 : 상품별 평균 평점 출력
- 

...
- OKR, KRI, NSM
- NSM 지표 의거해서 월별 주문건수가 00건 이하로 나오면 위기, 000건 이상이 나오면 긍정
- 현재 시점을 기준으로 최근 1개월간 전체 주문건수 확인
- 결론 : 최근 30일 이내 주문된 전체 총 건수 출력

### Python & MySQL (feat.SQL)

- pip install pymysql
- 패턴코드(Pattern Code)
    - Python에서 정해진 패턴을 활용해서 SQL 문법 실행

### MySQL 중·고급 문법 및 단계

- 다양한 SQL 함수
    - 문자열 함수 :
  1) LENGTH(string) : 문자의 길이를 반환하는 함수
  2) UPPER(string) : 특정 문자를 대문자로 변환시켜주는 함수
  3) LOWER(string) : 특정 문자를 소문자로 변환시켜주는 함수
  4) CONCAT(string1, string2, ...) : 복수의 문자열을 하나로 연결하는 함수  # ex.성과 이름 결합, 통신사와 번호 결합
  5) SUBSTRING(string, start, length) : 문자열에서 일부 문자열만 추출해주는 함수
    - 날짜/시간 함수 :
  1) NOW() : 현재날짜와 시간을 반환하는 함수
  2) CURDATE() : 현재 날짜를 반환하는 함수
  3) CURTIME() : 현재 시간을 반환하는 함수
  4) DATE_ADD(date, INTERVAL unit) : 특정 날짜에서 간격을 추가해주는 함수
      - unit type : MONTH/DAY/HOUR/MINUTE/SECOND
  6) DATE_SUB(date, INTERVAL unit) : 특정 날짜에서 간격을 빼주는 함수
      - unit type : MONTH/DAY/HOUR/MINUTE/SECOND
  7) EXTRACT(추출해오고자 하는 값 = field FROM 추출해오고자 하는 대상 = source)
  8) YEAR(), MONTH(), DAY(), HOUR(), MINUTE(), SECOND()
  9) DAYOFWEEK() : 특정 날짜의 요일을 반환 -> 1요일 : 일요일 / 7요일 : 토요일
  10) DAT_FORMAT() : 형식지정자로 값을 받아서 요일을 출력할 수 있음 -> %W, %a
      - %Y : 4자리 연도 2025
      - %y : 연도의 마지막 2자리 25
      - %M : 영문 월 June
      - %m : 월을 두자리 숫자로 표기 01, 02
      - %c : 월을 한자리 숫자로 표기 1, 2
      - %D : 일을 숫자 + 영문 접미사로 표기 01st, 04th
      - %d : 일을 두자리 숫자 31 10 09
      - %H : 시간을 24시간 형식의 두자리로 표기 15, 18
      - %h : 시간을 12시간 형식의 두자리로 표기 03, 09
      - %i : 분을 두자리 숫자로 표기
      - %s : 초를 두자리 숫자로 표기
  12) TIMESTAMPDIFF(unit, start_datetime, end_datetime) : 두 날짜 혹은 시간 값의 차이를 계산할 때 사용하는 함수   # VIP, 멤버십 -> 전략
        - unit type : MONTH/DAY/HOUR/MINUTE/SECOND
  13) ABS(number) : Absolute(절대적인) -> 절대값을 추출
  14) CEIL(number) : 올림처리
  15) FLOOR(number) : 버림처리
  16) ROUND(number) : 반올림처리 -> ROUND(숫자A, 숫자B) -> 숫자B가 최종적인 반올림의 결과값이 되도록
  17) SQRT(number) : 해당 숫자의 제곱근을 반환하는 함수
- SubQuery 고급활용
    : SQL쿼리문안에 또다른 SQL 쿼리문이 존재하는 것
    - 기본적으로 서브쿼리는 최근 문법인  JOIN ON 이라는 문법으로 대체 가능
    - 신문법에서는 JOIN ON -> JOIN USING()으로 대체 가능
    - 하지만 서브쿼리를 여전히 메인 문법으로 사용하고 있는 조직 존재
    - 과거 문법이어도 충분히 인지해야하는 경우가 빈번하게 발생하기 때문에 꼭 학습
      1) 서브쿼리는 특정 테이블의 필드값을 어떤 조건 하에 다른 테이블과 연결하여 값을 찾아와야하는 경우에 굉장히 많이 사용됨
      2) 서브쿼리를 FROM절에서 사용할 때에는 반드시 AS구문을 사용해야함
      3) 상관 서브쿼리 : 기존 서브쿼리와 달리 데이터를 참조하고자 하는 테이블이 동일한 경우, 해당 테이블을 사용하는 위치에 따라 상위에서 관리되고 있는 테이블을 참조할 수도 있는데 이 상황을 상관 서브쿼리라고 부름
  
- 집합 연산자
    - 합집합 : 서로 다른 집합을 하나로 합쳐서 사용할 때 -> 서로 다른 테이블을 하나로 합쳐서 사용할 때
       - UINON : 서로 다른 테이블을 하나로 결합할 때, 중복된 행은 제거
       - UNION ALL : 서로 다른 테이블을 하나로 결합할 때, 중복된 행까지 모두 포함
    - 교집합 : 서로 다른 테이블의 공통 부분만 추출할 때
        - INTERSECTION : 서로 다른 테이블의 공통 부분만 추출할 때
    - 차집합 : 서로 다른 테이블을 놓고 결합할 때, 어느 한쪽 영역에만 속해있는 부분만 가져올 때
        - EXCEPT : 서로 다른 테이블 결합 시, 어느한쪽 데이터만 찾아오고 싶을 때
- Transaction / COMMIT / ROLLBACK
    - 이미 만들어져있는 DB > TABLE 존재 -> TABLE 안에 값을 수정하고 싶음 -> WHERE 조건을 기준으로 수정 깜박했을 때
    - START TRANSACTION; -> 해당 명령어가 존재한다면, 데이터 수정 후 돌아갈 수 있는 환경을 세팅
    - ROLLBACK; -> START TRANSACTION;이 존재한다는 전제하에, 데이터 편집 전 단계로 돌려주는 명령어
    - COMMIT; -> 해당 명령어를 입력 및 실행하는 순간, 임시저장공간에 있던 데이터를 실제 데이터에 적용 (*COMMIT이후에는 ROLLBACK 기능이 적용될 수 없음)
- VIEW
    - VIEW는 실제 테이블을 기반으로 한 "가상 테이블"을 생성하고자 할 때 사용할 수 있는 명령어
    - VIEW를 사용하면 복잡한 쿼리문을 단순화 시킬 수 있음
    - CREATE VIEW "가상 테이블명" AS 실제 데이터
    - 만약, 동일한 이름으로 가상 테이블이 이미 존재하는 경우 추가로 생성하고자 할 때는 에러가 발생
    - CREATE OR REPLACE VIEW "가상 테이블명" AS 실제 데이터 => 신규로 가상테이블을 생성하거나 또는 덮어쓰기 가능!
    - DROP VIEW "가상 테이블명" => 해당 가상 테이블을 삭제·제거 하는 기능
- WITH
    - VIEW와 마찬가지로 "가상 테이블"을 생성하고자 할 때 사용할 수 있는 명령어
    - WITH절은 VIEW와 달리 구문을 실행하는 동안에만 작동하고 메모리 공간에 제거됨 => 값을 나중에 찾아올 수 없음
    - WITH "가상 테이블명" AS ()
- CASE WHEN
    - 프로그래밍 언어에서 자주 사용되는 if-else문 절과 매우 비슷
    - 어떤 조건에 따라서 출력을 다르게 하고자 할 때 많이 사용
    - ```
      CASE
          WHEN 조건1 THEN 결과1
          WHEN 조건2 THEN 결과2
          ....
          ELSE 파이널 결과
      END
      ```
- GROUP_CONCAT
    - MySQL에서 제공하는 문자열 집계 함수로, 그룹 내 여러 행을 하나의 문자열로 결합하는 역할
    - ```
      GROUP_CONCAT(expression)
      GROUP_CONCAT(expression SEPARATOR separator_string = 구분자 문자열 : x /)
      기본 구분자 값 => 쉼표 ,
      ```
    - 한개의 행 안에 여러개의 컬럼을 나눠서 출력하고 싶을 때 사용하는 함수
- 고급 윈도우